#!/bin/bash
cd ${0%/*} || exit 1;    # Run from this directory

# Set solver folder names
participant1="Fluid";
participant2="Solid";

# Set relative archive location
archiveloc="../results-archive/";

# Create overwrite function
overwrite() { echo -e "\r\033[1A\033[0K$@"; }

# Create folder for current result
read -p "Please enter a folder tag: " foldertag;
datestr=$(date '+%Y%m%d-%H%M-');
foldername="$datestr$foldertag";
destination="$archiveloc$foldername/";

if [ -d "$destination" ]; then
   echo "'$foldername' already exist, aborting.";
   exit 1;
else
   printf "Creating folder '$destination' ... ";
   mkdir "$destination";
   printf "done.\n";
fi

# Copying watchpoint files
cp "$participant2""/precice-Structure_Solver-watchpoint-"* "$destination"

# Copying Fluid and Solid log
cp "$participant1"".log" "$destination"
cp "$participant2"".log" "$destination"
cp "mbdyn.log" "$destination"


# Copying parameter files
# for precice v1.x and openfoam-mbdyn combination
printf "Copying simulation paramter files to .parameter folder ... ";

parameterloc="$destination"".parameter/";
mkdir "$parameterloc";
mkdir "$parameterloc$participant1";
mkdir "$parameterloc$participant2";

cp precice-config.xml "$parameterloc";

cp "$participant1"/precice-adapter-config.yml "$parameterloc$participant1";
cp -r "$participant1"/system "$parameterloc$participant1"/system;
cp -r "$participant1"/constant "$parameterloc$participant1"/constant;
cp -r "$participant1"/0 "$parameterloc$participant1"/0;

cp "$participant2"/predyn.py "$parameterloc$participant2";
cp "$participant2"/*.geo "$parameterloc$participant2";
cp "$participant2"/*.msh "$parameterloc$participant2";
cp "$participant2"/*.mbd "$parameterloc$participant2";
cp "$participant2"/mbdyn-config "$parameterloc$participant2";

printf "done.\n";

# Copying MBDyn results
printf "Copying MBDyn vtk files to mbdyn-vtk folder ... ";

solidloc="$destination""mbdyn-vtk";
mkdir "$solidloc";
cp "$participant2""/"*".vtk" "$solidloc""/";

printf "done.\n";

# Copying OpenFOAM results
fluidloc="$destination""openfoam";
mkdir "$fluidloc";

times=$(foamListTimes -case $participant1 2>&1);
IFS=$'\n' read -rd '' -a lines <<<"$times";

declare -i numlin=0;
echo "Copying OpenFOAM solution: [""$numlin""0/""${#lines[@]}"" timesteps copied.";
for time in "${lines[@]}"
do
    cp -r "$participant1"/"$time" "$fluidloc"/"$time";
    numlin+=1;
    overwrite "Copying OpenFOAM solution: [""$numlin""/""${#lines[@]}""] timesteps copied.";
done

cp -r "$participant1""/postProcessing" "$fluidloc"/postProcessing;
cp -r "$participant1""/constant" "$fluidloc"/constant;
cp "$participant1""/Fluid.foam" "$fluidloc"/Fluid.foam;

# Finishing up
echo "Archiving files complete!";
